export const ContentNavButtonMap = [
  {
    Continent: "Europe",
    arraylist: [
      { town: "Paris, France" },
      { town: "London, England" },
      { town: "Berlin, Germany" },
      { town: "Rome, Italy" },
      { town: "Dublin, Ireland" },
      { town: "Edinburgh, Scotland" },
      { town: "Barcelona, Spain" },
      { town: "Venice, Italy" },
      { town: "Madrid, Spain" },
      { town: "Pargue, Czech Republic" },
      { town: "Vienna, Austria" },
      { town: "Lisbon, Portugal" },
      { town: "Athens, Greece" },
      { town: "Porto, Portugal" },
      { town: "Budapest, Hungary" },
      { town: "Stockholm, Sweden" },
    ],
  },

  {
    Continent: "Aisa",
    arraylist: [
      { town: "Singapore" },
      { town: "Kuala Lumpur, Malaysia" },
      { town: "Bangkok, Thailand" },
      { town: "Taipei, Taiwan" },
      { town: "Seoul, South Korea" },
      { town: "Hong Kong, China" },
      { town: "Macau, China" },
      { town: "Shanghai, China" },
      { town: "Hanoi, Vietnam" },
      { town: "Tokyo, Japan" },
      { town: "Bali, Indonesia" },
      { town: "Hoi An, Vietnam" },
      { town: "Luang Prabang, Laos" },
      { town: "Kyoto, Japan" },
    ],
  },

  {
    Continent: "North America",
    arraylist: [
      { town: "Ottawa, Canada" },
      { town: "Toronto, Canada" },
      { town: "Niagara-on-the-Lake, Canada" },
      { town: "Vancouver, Canada" },
      { town: "Edmonton, Canada" },
      { town: "Montreal, Canada" },
      { town: "Mexico City, Mexico" },
      { town: "Tulum, Mexico" },
      { town: "Havana, Cuba" },
      { town: "San Diego, USA" },
      { town: "Virginia Beach. USA" },
      { town: "New Orleans, USA" },
      { town: "New York, USA" },
      { town: "Seattle, USA" },
      { town: "San Franciso, USA" },
    ],
  },
  {
    Continent: "South America",
    arraylist: [
      { town: "Rio De Janerio, Brazil" },
      { town: "Cuso, Peru" },
      { town: "Santiago, Chile" },
      { town: "Ushuaia, Argentina" },
      { town: "Buenos Aires, Argentina" },
      { town: "Montevideo, Uruguay" },
      { town: "San Pedro de Atacama, Chile" },
      { town: "Sao Paulo, Brazil" },
      { town: "Paramaribo, Suriname" },
      { town: "Lima, Peru" },
      { town: "El Calafate, Argentina" },
      { town: "Bogota, Colombia" },
      { town: "La Paz, Bolivia" },
    ],
  },
  {
    Continent: "North Africa",
    arraylist: [
      { town: "Cairo, Egypt" },
      { town: "Marrakesh, Morocco" },
      { town: "Luxor, Egypt" },
      { town: "Fes Morocco" },
      { town: "Siwa Oasis, Egypt" },
      { town: "Tunis, Tunisia" },
      { town: "Algiers, Algeria" },
      { town: "Casablanca, Morocco" },
      { town: "Aswan, Egypt" },
      { town: "Alexandria, Egypt" },
      { town: "Chefchaouen, Morocco" },
      { town: "Fes, Morocco" },
      { town: "Rabat, Morocco" },
      { town: "Tangier, Morocco" },
    ],
  },
];
